/* eslint-disable @typescript-eslint/no-explicit-any */
import { auth } from "@/auth";
import { AdminSidebar } from "@/components/admin/admin-sidebar";
import { UserMenu } from "@/components/app/user-menu";
import { ThemeToggle } from "@/components/theme/theme-toggle";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppName } from "@/lib/env";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  if (!session?.user) {
    redirect("/login");
  }

  return (
    <SidebarProvider>
      <AdminSidebar />
      <main className="flex flex-col flex-1">
        <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4 bg-card">
          <div className="flex items-center gap-2">
            <SidebarTrigger />
            <div className="font-semibold text-base sm:text-sm">
              {AppName} Admin
            </div>
          </div>
          <div className="ml-auto space-x-2">
            <ThemeToggle />
            <UserMenu user={session.user as any} />
          </div>
        </header>
        <div className="flex-1 bg-muted p-4">{children}</div>
      </main>
    </SidebarProvider>
  );
}
