/* eslint-disable @typescript-eslint/no-explicit-any */
import { auth } from "@/auth";
import { UserMenu } from "@/components/app/user-menu";
import { DashboardSidebar } from "@/components/dashboard/dashboard-sidebar";
import { ThemeToggle } from "@/components/theme/theme-toggle";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppName } from "@/lib/env";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  if (!session?.user) {
    redirect("/login");
  }
  return (
    <SidebarProvider>
      <DashboardSidebar />
      <main className="flex flex-col flex-1">
        <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4 bg-card">
          <div className="flex items-center gap-2">
            <SidebarTrigger />
            <div className="font-semibold text-base sm:text-sm">{AppName}</div>
          </div>
          <div className="ml-auto space-x-2">
            <ThemeToggle />
            <UserMenu user={session.user as any} />
            {/* Pasar el usuario con el nombre del rol */}
          </div>
        </header>
        <div className="flex-1 bg-muted p-4">{children}</div>
      </main>
    </SidebarProvider>
  );
}
