import Footer from "@/components/landing/footer";
import Header from "@/components/landing/header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Términos de Servicio",
  description: "Generated by create next app",
};

const TermsOfServicePage = () => {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1 bg-muted"></main>
      <Footer />
    </div>
  );
};

export default TermsOfServicePage;
